#! /bin/bash

# This script follows the procedure for running purge_haplotigs as detailed in:
# https://bitbucket.org/mroachawri/purge_haplotigs/src/master/
#
# IMPORTANT: the cutoffs provide to purge_haplotigs cov must be set manually.
#
# Scripts run on the Stanford Genomics Cluster

#SBATCH --job-name=purge_haps1
#SBATCH --time=72:00:00
#SBATCH --partition=batch
#SBATCH --account=emordeca
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=600G
#SBATCH --output=purge_haps1.out

cd /labs/emordeca/LowAndULsubreads/

module load minimap2/2.17
module load purge_haplotigs/1.1.2
module load samtools/0.1.19

# step 1: Map low and ultralow ccs reads to the draft assembly, then parse with sam tools

minimap2 -t 16 -ax asm20 assembly.fasta  m64047_211218_171850.ccs.fastq m64047_211230_040352.ccs.fastq --secondary=no | 
samtools sort -m 1G -o Ae.sierrensis.aligned.bam -T Ae.sierrensis.ali

# step 2: Generate the coverage histogram

purge_haplotigs hist -b Ae.sierrensis.aligned.bam -g assembly.fasta -t 16

